SPOOL solution2
SET SERVEROUTPUT ON
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 300
SET PAGESIZE 200 
SET SERVEROUTPUT ON 

DECLARE
    ID_O    ORDERS.ORDER_ID%TYPE;
    NAME_C  CUSTOMER.COMPANY_NAME%TYPE;
    DATE_O  ORDERS.ORDER_DATE%TYPE;
    ROW_COUNT   NUMBER(2) :=1;
    CURSOR LASTFIVE IS 
        SELECT ORDERS.ORDER_ID, CUSTOMER.COMPANY_NAME, ORDERS.ORDER_DATE
        FROM ORDERS INNER JOIN CUSTOMER ON (ORDERS.CUSTOMER_CODE = CUSTOMER.CUSTOMER_CODE)
        ORDER BY ORDERS.ORDER_DATE DESC;    
BEGIN
    OPEN LASTFIVE;
    LOOP
    FETCH LASTFIVE INTO ID_O, NAME_C, DATE_O;
        IF LASTFIVE%NOTFOUND THEN
            EXIT;
        END IF;
        DBMS_OUTPUT.PUT_LINE('Order id: '   ||  ID_O);
        DBMS_OUTPUT.PUT_LINE('Order date: '   ||  TO_CHAR(DATE_O,'DD-MON-YY'));
        DBMS_OUTPUT.PUT_LINE('Company name: '   ||  NAME_C);
        DBMS_OUTPUT.PUT_LINE('=======================================');
        ROW_COUNT := ROW_COUNT + 1;
        EXIT WHEN LASTFIVE%ROWCOUNT = 5;        
    END LOOP;
    CLOSE LASTFIVE;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM || '   ' || SQLCODE);
END;
/
spool off
