SPOOL solution1
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 300
SET PAGESIZE 200
/*-------------------1--------------------*/

EXPLAIN PLAN FOR 
SELECT * 
FROM ORDER_DETAIL
WHERE PRODUCT_NAME = 'BOLT' AND QUANTITY > 100;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX ORDER_DPQ ON ORDER_DETAIL(PRODUCT_NAME, QUANTITY);

EXPLAIN PLAN FOR 
SELECT * 
FROM ORDER_DETAIL
WHERE PRODUCT_NAME = 'BOLT' AND QUANTITY > 100;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

DROP INDEX ORDER_DPQ;

/*-------------------2--------------------*/
EXPLAIN PLAN FOR
SELECT DISTINCT CATEGORY_NAME
FROM PRODUCT;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX PRODUCT_C ON PRODUCT(CATEGORY_NAME);

EXPLAIN PLAN FOR
SELECT DISTINCT CATEGORY_NAME
FROM PRODUCT;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

DROP INDEX PRODUCT_C;

/*-------------------3--------------------*/
EXPLAIN PLAN FOR 
SELECT UNIT_PRICE
FROM ORDER_DETAIL
WHERE QUANTITY IN (100, 200, 300) OR DISCOUNT = 0.01;

SELECT * 
FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX ORDER_DQD ON ORDER_DETAIL(QUANTITY, DISCOUNT,UNIT_PRICE);

EXPLAIN PLAN FOR 
SELECT UNIT_PRICE
FROM ORDER_DETAIL
WHERE QUANTITY IN (100, 200, 300) OR DISCOUNT = 0.01;

SELECT * 
FROM TABLE(DBMS_XPLAN.DISPLAY);

DROP INDEX ORDER_DQD;

/*-------------------4--------------------*/
EXPLAIN PLAN FOR
SELECT CATEGORY_NAME, SUPPLIER_NAME, COUNT(*)
FROM PRODUCT 
GROUP BY CATEGORY_NAME, SUPPLIER_NAME;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX PRODUCT_CS ON PRODUCT(CATEGORY_NAME, SUPPLIER_NAME);

EXPLAIN PLAN FOR
SELECT CATEGORY_NAME, SUPPLIER_NAME, COUNT(*)
FROM PRODUCT 
GROUP BY CATEGORY_NAME, SUPPLIER_NAME;

SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

DROP INDEX PRODUCT_CS;

/*-------------------5--------------------*/
EXPLAIN PLAN FOR 
SELECT SUPPLIER_NAME, UNIT_PRICE
FROM PRODUCT
ORDER BY UNIT_PRICE, QUANTITY_PER_UNIT;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX PRODUCT_UQ ON PRODUCT(UNIT_PRICE, QUANTITY_PER_UNIT,SUPPLIER_NAME);

EXPLAIN PLAN FOR 
SELECT SUPPLIER_NAME, UNIT_PRICE
FROM PRODUCT
ORDER BY UNIT_PRICE, QUANTITY_PER_UNIT;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

DROP INDEX PRODUCT_UQ;

SPOOL OFF