SPOOL solution4
SET SERVEROUTPUT ON
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

CREATE OR REPLACE FUNCTION TOTAL_ORDERS(INPUT_COMPANY_NAME CUSTOMER.COMPANY_NAME%TYPE)
RETURN NUMBER IS
    TOTAL_NUMBERS   NUMBER;
BEGIN
    --EXECUTING THE FUCNTION
    SELECT COUNT(*) INTO TOTAL_NUMBERS
    FROM ORDERS INNER JOIN CUSTOMER ON (ORDERS.CUSTOMER_CODE = CUSTOMER.CUSTOMER_CODE)
    WHERE  CUSTOMER.COMPANY_NAME = INPUT_COMPANY_NAME
    GROUP BY ORDERS.CUSTOMER_CODE;
    RETURN TOTAL_NUMBERS;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);    
    COMMIT;
END;
/
--Use the function
SELECT COMPANY_NAME,ADDRESS,TOTAL_ORDERS(COMPANY_NAME)
FROM CUSTOMER
WHERE TOTAL_ORDERS(COMPANY_NAME)>2 AND TOTAL_ORDERS(COMPANY_NAME)<6;

SPOOL OFF
