SPOOL solution3
SET SERVEROUTPUT ON
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 300
SET PAGESIZE 200
SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE INSERT_ORDER_DETAIL(INPUT_ORDER_ID NUMBER, INPUT_PRODUCT_NAME VARCHAR, INPUT_PRICE NUMBER, INPUT_QUANTITY NUMBER, INPUT_DISCOUNT NUMBER)
IS 
    TEST_DISCONTINUED PRODUCT.DISCONTINUED%TYPE;
BEGIN
    SELECT DISCONTINUED INTO TEST_DISCONTINUED
    FROM PRODUCT
    WHERE PRODUCT_NAME = INPUT_PRODUCT_NAME;
    --CHECKING IF THE PRODUCT IS NTO DISCONTINUED
    IF(TEST_DISCONTINUED != 'N') THEN
        DBMS_OUTPUT.PUT_LINE('ROW INSERT FAILED: THE PRODUCT IS DISCONTINUED!');
    ELSE
        INSERT INTO ORDER_DETAIL VALUES(INPUT_ORDER_ID, INPUT_PRODUCT_NAME, INPUT_PRICE, INPUT_QUANTITY, INPUT_DISCOUNT);
        DBMS_OUTPUT.PUT_LINE('ROW INSERT SUCCESSFUL');
    END IF;  
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('DATA NOT FOUND!');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
    COMMIT;
END INSERT_ORDER_DETAIL;
/

--PRODUCT DISC: N
EXECUTE INSERT_ORDER_DETAIL(248, 'Aniseed Syrup', 8, 30, 0);
--PRODUCT DISC: Y
EXECUTE INSERT_ORDER_DETAIL(253,'Chef Anton''s Gumbo Mix', 50, 30, 0);

SPOOL OFF